/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AuthResponse {
  token?: string;
  data?: {
    access_token?: string;
};
  msg?: string;
  statusCode?: number;
  timestamp?: number;
}
