/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { UserDto } from '../models/user-dto';
export interface ProfileDto {
  backImage?: Blob;
  backImg?: string;
  blurImage?: Blob;
  blurImg?: string;
  boobSize?: number;
  faceImage?: Blob;
  faceImg?: string;
  frontImage?: Blob;
  frontImg?: string;
  height?: number;
  hipSize?: number;
  id?: number;
  sideImage?: Blob;
  sideImg?: string;
  userDTO?: UserDto;
  userId?: number;
  waistSize?: number;
}
